### ISSUE TITLE
Python 2.7 - ImportError: cannot import name requests

### ISSUE THREAD

**Issue by johnjohndoe** [Bolton-and-Menk-GIS/restapi#1]
I am trying to run your package with Python 2.7.10 on Ubuntu 15.10. I installed it like this:

``` sh
$ pip install git+git://github.com/Bolton-and-Menk-GIS/restapi.git@master --user
```

Then in the shell:

``` sh
$ python                                                                         
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2

>>> import restapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/restapi/__init__.py", line 12, in <module>
    import admin
  File "/home/user/.local/lib/python2.7/site-packages/restapi/admin/__init__.py", line 2, in <module>
    from _base import * 
  File "/home/user/.local/lib/python2.7/site-packages/restapi/admin/_base.py", line 12, in <module>
    from .. import requests
ImportError: cannot import name requests
```

**Comment by CalebM1987** [comment]
That is strange, I cannot reproduce the issue on Windows and unfortunately I do not have an Ubuntu machine to test on.  Can you verify that there is a folder called requests within the restapi folder?  Send any replies to my email at caleb.mackey@gmail.com.

**Comment by johnjohndoe** [comment]
The installation folder `~/.local/lib/python2.7/site-packages/restapi/` contains the following:

```
admin/
arc_restapi.py
arc_restapi.pyc
__init__.py
__init__.pyc
open_restapi.py
open_restapi.pyc
rest_utils.py
rest_utils.pyc
shapefile/
shp_helper.py
shp_helper.pyc
test/
```

**Comment by CalebM1987** [comment]
Looks like the requests module isn't coming through with the setup.py.  It should be in the top directory.  I'll see if I can fix it.

**Comment by CalebM1987** [comment]
I have fixed the setup issues.  Next time you run the "setup.py install" from the CMD it should bring requests over properly now.
