### ISSUE TITLE
'ArcServer' object has no attribute 'get_MapService' Python 3

### ISSUE THREAD

**Issue by carlsunderman** [Bolton-and-Menk-GIS/restapi#19]
Using the sample code:
<b>connect NOAA ArcGIS Server Instance</b>
rest_url = 'https://idpgis.ncep.noaa.gov/arcgis/rest/services'

<b>no authentication is required, so no username and password are supplied</b>
ags = restapi.ArcServer(rest_url)

bla = ags.get_MapService('/NOAA/MPA_Inventory_Fishing')

<b>I get the following error</b>
AttributeError: 'ArcServer' object has no attribute 'get_MapService'

Am i missing something?

**Comment by CalebM1987** [comment]
Sorry, that was actually an issue with the documentation.  The `README.md` desperately needs to be updated and I'm hoping to generate some `sphinx` docs when I can get around to cleaning this package up.  Here is what you actually want to do, the `get_MapService()` method was deprecated long ago and replaced with `getService()`, which of course is my fault for not updating the readme.  Try this:

```py
rest_url = 'https://idpgis.ncep.noaa.gov/arcgis/rest/services'
ags = restapi.ArcServer(rest_url)
bla = ags.getService('/NOAA/MPA_Inventory_Fishing')  # returns an instance of MapService
```

**Comment by CalebM1987** [comment]
I am going to close this as I did not receive a response.  I will assume this question was answered.
