### ISSUE TITLE
no module named shp_helper

### ISSUE THREAD

**Issue by xisphias** [Bolton-and-Menk-GIS/restapi#23]
The restapi seems to have installed fine, but when trying to export a shapefile iI get a no module found error.  

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-21-f87e21d19313> in <module>
      9 # export layer to shapefile (can also call from Map Service)
     10 output = os.path.join(folder, 'ESRI_citations.shp')
---> 11 lyr.layer_to_fc(output, where=query, sr=3857)
     12 
     13 # export to KMZ

~/Documents/GitHub/restapi/restapi/common_types.py in export_layer(self, out_fc, fields, where, records, params, exceed_limit, sr, include_domains, include_attachments, qualified_fieldnames, **kwargs)
   1540                         field.domain = f_dict[field.name].get(DOMAIN)
   1541 
-> 1542                 return exportFeatureSet(fs, out_fc, include_domains)
   1543 
   1544 ##            if has_arcpy and all([include_attachments, self.hasAttachments, fs.OIDFieldName])::

~/Documents/GitHub/restapi/restapi/common_types.py in exportFeatureSet_os(feature_set, out_fc, outSR, **kwargs)
    277         """
    278 
--> 279         import shp_helper
    280         from .shapefile import shapefile
    281         out_fc = validate_name(out_fc)

ModuleNotFoundError: No module named 'shp_helper'

**Comment by CalebM1987** [comment]
Thanks for pointing this out, I have been changing some things around.  I will look into this.

**Comment by CalebM1987** [comment]
This has now been fixed with my most recent patch.  Tested on a Macbook Pro with python version 3.7.x.
