### ISSUE TITLE
Installation failed with Python 2.7

### ISSUE THREAD

**Issue by mycana** [Bolton-and-Menk-GIS/restapi#26]
Here is the error message:

File "c:\appdata\local\temp\2\pip-install-o0yrzj\bmi-arcgis-restapi\setup.py", line 6, in <module>
        with open(os.path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
PS C:\Python27\ArcGIS10.6\Scripts> .\pip.exe install bmi-arcgis-restapi

**Comment by mycana** [comment]
Found a way to install it. Thanks.

**Comment by CalebM1987** [comment]
Reopening this issue as I have received an email about this today.  Another person was able to reproduce this error:

`C:\Python27\ArcGIS10.7\Scripts>pip install bmi-arcgis-restapi

Collecting bmi-arcgis-restapi

  Using cached https://files.pythonhosted.org/packages/29/89/d1bb161a032acc83f0fe38bbf9db553562836555deabf00c15d7812f003c/bmi-arcgis-restapi-1.0.2.tar.gz

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "c:\users\kgerha~1\appdata\local\temp\pip-install-qxh3aq\bmi-arcgis-restapi\setup.py", line 6, in <module>

        with open(os.path.join(this_directory, 'README.md'), encoding='utf-8') as f:

    TypeError: 'encoding' is an invalid keyword argument for this function

 

    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in c:\users\kgerha~1\appdata\local\temp\pip-install-qxh3aq\bmi-arcgis-restapi\`

**Comment by philnagel** [comment]
This should now be fixed in https://github.com/Bolton-and-Menk-GIS/restapi/commit/8ba5ad65b665948ebc1f1ab906767c670499ca6f (Release 1.0.3) 
Please give it a try. I will close this for now, but feel free to re-open if this issue persists.
