### ISSUE TITLE
Should `urllib3` be an install dependency?

### ISSUE THREAD

**Issue by philnagel** [Bolton-and-Menk-GIS/restapi#27]
Should `urllib3` be an install dependency?

**Comment by cartograham** [comment]
@philnagel  - after installation of `restapi`, I was not able to import it.  The error message reported out that urllib.exceptions could not be found.
`pip install urllib3` worked for me; I could install and run this package after that.

Hope this helps

**Comment by philnagel** [comment]
Thanks for the reminder to follow up and for confirming this.
https://github.com/Bolton-and-Menk-GIS/restapi/commit/4703149744f3041da08189e7b22b38962307f38c

**Comment by philnagel** [comment]
Fixed in [1.0.5](https://github.com/Bolton-and-Menk-GIS/restapi/releases/tag/1.0.5)
