### ISSUE TITLE
Python 2.7 - AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by johnjohndoe** [Bolton-and-Menk-GIS/restapi#3]
I am trying to run your package with Python 2.7.10 on Ubuntu 15.10. I installed it like this:

``` sh
$ pip install git+git://github.com/Bolton-and-Menk-GIS/restapi.git@master --user
```

Then in the shell:

``` sh
$ python                                                                         
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2

>>> import restapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "restapi/__init__.py", line 12, in <module>
    import admin
  File "restapi/admin/__init__.py", line 2, in <module>
    from _base import * 
  File "restapi/admin/_base.py", line 12, in <module>
    from .. import requests
  File "restapi/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "restapi/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

**Comment by CalebM1987** [comment]
Is this an ubuntu issue?  When I import ssl, I have the attribute ssl.PROTOCOL_SSLv3 (the value is 1).  I am using Windows 7.

**Comment by johnjohndoe** [comment]
The error does not immediately occur when I install your package in a clean environment such as via [virtualenv](https://virtualenv.readthedocs.org/en/latest/). There are **other errors showing up**, though. Please setup a clean environment yourself to ensure that all dependencies are satisfied after installation of the package.

**Comment by CalebM1987** [comment]
I just ran the install on a new windows machine and cannot reproduce the issue.  Everything is working fine for me.  What other errors are you getting?  Whatever the case, these all appear to be from requests.  As a workaround can you install requests and place it in the restapi package?

The error you posted doesn't make sense to me. ssl is a standard library module so I don't know why you're missing the 'PROTOCOL_SSLv3' attribute unless it is not supported in ubuntu or it is not included in whatever version of Python you're running.  What version of Python are you running?

It is also worth mentioning that I am installing by cloning the repo then using the command prompt to install:  

cd %the folder location%
setup.py install

**Comment by johnjohndoe** [comment]
Please mind there can be interferences with the packages being installed with the system Python. Therefore, a empty/clean environment is mandatory to ensure all dependencies are satisfied.

I stated my Python version at the first post. The first error is missing python-dateutil, ... I did not try to resolve further errors which succeeded.

**Comment by CalebM1987** [comment]
I am not  sure how to fix this issue.  However, I did a quick google search and there appears to be many problems associated with requests/ssl/OpenSSL on ubuntu.  This is an issue you should post to the requests repo as the import errors you are receiving are related to that.

This is directly related to your first error:
https://github.com/threatstream/shockpot/issues/8

http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

Hopefully this helps.

**Comment by johnjohndoe** [comment]
As I already mentioned: the `PROTOCOL_SSLv3` error does not occur when I install the package in a virtual environment set up with *virtualenv*. Feel free to close this issue.

Besides this it would be great if you can set up *virtualenv* yourself to check the other errors. I strongly recommend starting to work with this now. It is mentioned in the first link, too.
