### ISSUE TITLE
 SSLError

### ISSUE THREAD

**Issue by MeghaDhingraCal** [Bolton-and-Menk-GIS/restapi#30]
When I try to put in the url to the layer (no password) and the proxy, I get an error that says (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)')))

**Comment by philnagel** [comment]
Could you post your code and the full traceback please? If you don't to share the server URLs, please obfuscate the domain name, but leave other things like protocol and ports intact.

Usually this error means that you are trying to access a non-ssl server or port over ssl. So your URL might be something like `https://example.com:80/...`, where that should be `https://example.com:443/...` or `http://example.com:80/...`

**Comment by MeghaDhingraCal** [comment]
Hello, thank you so much.
My code is 
import restapi
rest_url = "https://hazards.fema.gov/gis/nfhl/rest/services/FIRMette/NFHLREST_FIRMette/MapServer/27"
ags = restapi.ArcServer(rest_url, proxy="https://removed").
The proxy has port 8080. How do I know the correct port I need to change it?

The error is below. I was also wondering if there is a limit to the number of calls to the arcgis api since I need to set getAll
or exceed_limit=True and there are 3 million total records, with max_record = 1000. Thank you so much.
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
C:\\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    671                 headers=headers,
--> 672                 chunked=chunked,
    673             )

C:\\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    375         try:
--> 376             self._validate_conn(conn)
    377         except (SocketTimeout, BaseSSLError) as e:

C:\\lib\site-packages\urllib3\connectionpool.py in _validate_conn(self, conn)
    993         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
--> 994             conn.connect()
    995 

C:\\lib\site-packages\urllib3\connection.py in connect(self)
    359             server_hostname=server_hostname,
--> 360             ssl_context=context,
    361         )

C:\lib\site-packages\urllib3\util\ssl_.py in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password)
    369         if HAS_SNI and server_hostname is not None:
--> 370             return context.wrap_socket(sock, server_hostname=server_hostname)
    371 

C:\Users\Anaconda3\lib\ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    422             context=self,
--> 423             session=session
    424         )

C:\\lib\ssl.py in _create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
    869                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
--> 870                     self.do_handshake()
    871             except (OSError, ValueError):

C:\lib\ssl.py in do_handshake(self, block)
   1138                 self.settimeout(None)
-> 1139             self._sslobj.do_handshake()
   1140         finally:

**SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)**

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
C:\Users\\Anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

C:\Users\\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    719             retries = retries.increment(
--> 720                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    721             )

C:\Users\\Anaconda3\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    435         if new_retry.is_exhausted():
--> 436             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    437 

MaxRetryError: HTTPSConnectionPool(host='proxy', port=8080): Max retries exceeded with url: /?https://hazards.fema.gov/gis/nfhl/rest/services/FIRMette/NFHLREST_FIRMette/MapServer/27?f=json (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
<ipython-input-5-9a50e98363a8> in <module>
      1 import restapi
      2 rest_url = "https://hazards.fema.gov/gis/nfhl/rest/services/FIRMette/NFHLREST_FIRMette/MapServer/27"
----> 3 ags = restapi.ArcServer(rest_url, proxy="https://proxy")
      4 print(ags.services)

C:\Users\\Anaconda3\lib\site-packages\restapi\common_types.py in __init__(self, url, usr, pw, token, proxy, referer)
    748 
    749     def __init__(self, url, usr='', pw='', token='', proxy=None, referer=None):
--> 750         super(ArcServer, self).__init__(url, usr, pw, token, proxy, referer)
    751         self.service_cache = []
    752 

C:\Users\\Anaconda3\lib\site-packages\restapi\rest_utils.py in __init__(self, url, usr, pw, token, proxy, referer, **kwargs)
    855             if self.token.get(IS_AGOL) or self.token.get(IS_PORTAL):
    856                 params[TOKEN] = str(self.token)
--> 857         self.raw_response = do_post(self.url, params, ret_json=False, token=self.token, cookies=self._cookie, proxy=self._proxy, referer=self._referer)
    858         self.elapsed = self.raw_response.elapsed
    859         self.response = self.raw_response.json()

C:\Users\\lib\site-packages\restapi\rest_utils.py in do_post(service, params, ret_json, token, cookies, proxy, referer, **kwargs)
    273 
    274     if proxy:
--> 275         r = do_proxy_request(proxy, service, params, referer)
    276         ID_MANAGER.proxies[service.split('/rest')[0].lower() + '/rest/services'] = proxy
    277     else:

C:\\lib\site-packages\restapi\rest_utils.py in do_proxy_request(proxy, url, params, referer, ret_json)
    323         headers[enums.headers.referer] = referer
    324     #return requests.post('{}?{}?f={}&{}'.format(proxy, url, frmat, p).rstrip('&'), verify=False, headers=headers)
--> 325     return requests.post('{}?{}?f={}'.format(proxy, url, frmat).rstrip('&'), params, verify=False, headers=headers)
    326 
    327 def guess_proxy_url(domain):

C:\Users\\lib\site-packages\requests\api.py in post(url, data, json, **kwargs)
    117     """
    118 
--> 119     return request('post', url, data=data, json=json, **kwargs)
    120 
    121 

C:\Users\\lib\site-packages\requests\api.py in request(method, url, **kwargs)
     59     # cases, and look like a memory leak in others.
     60     with sessions.Session() as session:
---> 61         return session.request(method=method, url=url, **kwargs)
     62 
     63 

C:\\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    528         }
    529         send_kwargs.update(settings)
--> 530         resp = self.send(prep, **send_kwargs)
    531 
    532         return resp

C:\\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    641 
    642         # Send the request
--> 643         r = adapter.send(request, **kwargs)
    644 
    645         # Total elapsed time of the request (approximately)

C:\\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    512             if isinstance(e.reason, _SSLError):
    513                 # This branch is for urllib3 v1.22 and later.
--> 514                 raise SSLError(e, request=request)
    515 
    516             raise ConnectionError(e, request=request)

SSLError: HTTPSConnectionPool(host='proxy', port=8080): Max retries exceeded with url: /?https://hazards.fema.gov/gis/nfhl/rest/services/FIRMette/NFHLREST_FIRMette/MapServer/27?f=json (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)')))

**Comment by philnagel** [comment]
Thank you for posting the additional info!
A couple of things I'm seeing:

1. Most likely the 8080 port indicates the proxy is HTTP not HTTPS. Please try using the `http://` prefix instead of `s`.
2. It looks like based on the format of your proxy URL that this is a regular HTTP proxy. The proxy parameter is only for [ESRI Resource Proxy](https://github.com/Esri/resource-proxy) pages. If this is not an ESRI Resource proxy, you cannot use it like that. Your service is openly accessible, so most likely you shouldn't need one.
If you need a proxy for network access, you can take a look at the `sessions` branch of this repository. This is a new features currently under development that lets you pass parameters directly to the underlying `requests` methods that make the request to the server. There is some usage info in the [readme ](https://github.com/Bolton-and-Menk-GIS/restapi/tree/sessions#advanced-usage)in that branch.

**Comment by philnagel** [comment]
@MeghaDhingraCal Haven't heard from you in a while, I will assume the previous comment resolved your issue. I will close this for now, feel free to comment here again if you are still having trouble.
