### ISSUE TITLE
The problem about the length of the character field exported from featureserver is only 254 characters

### ISSUE THREAD

**Issue by poplarsun** [Bolton-and-Menk-GIS/restapi#31]
After running the code` export_layer(shp)` , the field which is `String` of the shapefile is only 254 characters.
I need the field is `TEXT(1000+)`.

**Comment by CalebM1987** [comment]
This is a limitation of the [dBase Format used by shapefiles](https://gis.stackexchange.com/a/75096/9899).  If you want longer text fields, you'll need to use a File Geodatabase or Remote GDB (SDE) Feature Class.

I'm going to close as the error has nothing to do with this package.

**Comment by poplarsun** [comment]
Thanks!
