### ISSUE TITLE
Is there a way to get the number of records without doing a query with exceed_limit=true?

### ISSUE THREAD

**Issue by phauly** [Bolton-and-Menk-GIS/restapi#33]
I'm wondering if there is a way to get the number of records without doing a complete query.
Doing a query with exceed_limit=True and then accessing count as in the example in the documentation is an option but it is very time consuming and resource demanding for the server I guess.
Thank you!

**Comment by phauly** [comment]
I've seen that in the query page there is the option for "Return Count Only"

**Comment by phauly** [comment]
Yep, just found looking in the code for "Return Count Only" that there is returnCountOnly and in fact lyr.query(returnCountOnly=True) works fine. I'm going to close the issue, sorry for bothering you!

**Comment by CalebM1987** [comment]
Yes, that is the solution.  Thank you for closing this.  One thing we need to do is update the documentation for this package to make it easier to find information like that.  Most of the samples in the README are from 4-5 years ago when I first published this package 😬
