### ISSUE TITLE
Can’t pass outSR to query

### ISSUE THREAD

**Issue by ghost** [Bolton-and-Menk-GIS/restapi#39]
I'm interested in passing outSR to query. Is it possible via kwargs? Tried several ways (escaped string, raw string) but it doesn't seem to work. Wrote my own url_builder, and it is working fine. However I would like to do it with restapi. Please advise.

**Comment by philnagel** [comment]
Can you show some example of how you are passing the spatial reference? You are correct, passing a kwarg of `outSR` should work. The value should be either the WKID (integer, not string), or you can pass a `dict` formatted like [spatialReference JSON object](https://developers.arcgis.com/documentation/common-data-types/geometry-objects.htm#GUID-DFF0E738-5A42-40BC-A811-ACCB5814BABC).

So for example to request the result in WGS1984, you could pass `outSR=4326` or `outSR={"wkid" = 4326}`

**Comment by ghost** [comment]
Great! That solves the problem. I was passing WKTEXT instead. Thanks for prompt response!
