### ISSUE TITLE
Add explicit support for Python 3.9, 3.10, 3.11

### ISSUE THREAD

**Issue by DeflateAwning** [Bolton-and-Menk-GIS/restapi#52]
In the pypi page, it says your latest supported python version is 3.8. It'd be great if you could add official support for all later versions. https://pypi.org/project/bmi-arcgis-restapi/

**Comment by philnagel** [comment]
Thanks for letting us know. I'll be pushing that in a moment. Just a heads-up, we are using 3.9 currently so that is the only version this is reasonably tested with. Though I don't see any reason why there will be problems with the higher versions.
