### ISSUE TITLE
SNIMissingWarning from urllib3 causes dependency conflict 

### ISSUE THREAD

**Issue by adamknaze** [Bolton-and-Menk-GIS/restapi#53]
Hi, there seems to be a dependency conflict for Python 3.10+

In rest_utils.py you import SNIMissingWarning warning from urllib3 in order to disable it:

```
from urllib3.exceptions import InsecureRequestWarning, InsecurePlatformWarning, SNIMissingWarning
...
# disable ssl warnings
for warning in [InsecurePlatformWarning, InsecureRequestWarning, SNIMissingWarning]:
    disable_warnings(warning)
```

However, for urllib3 version 2+ this will cause ImportError, since the warning was removed along with support for OpenSSL <1.1.1 ([issue](https://github.com/urllib3/urllib3/issues/2168)).

Downgrading to urllib3 versions <2 doesn't work either, since these are not compatible with Python 3.10+

I removed the import since I'm using Python 3.11 and urllib 2.0.4. Doing a try catch would solve the issue, but I'm not sure if it's worth it.

**Comment by philnagel** [comment]
Agreed, probably not necessary to have those disabled, guessing it can be done via the requests session client now. Thank you for bring this up!
