### ISSUE TITLE
Python 2.7.8 Proxy Authentication

### ISSUE THREAD

**Issue by MikeTownshend** [Bolton-and-Menk-GIS/restapi#6]
Good Morning,

I am currently able to use version 0.1 to export layers in a Map Service to a local shape file while not behind a corporate fire wall.  However, when I am behind a corporate fire wall the exiting prod version 0.1 throws an error as does the Devel version 1.0.

I believe the issue is that our proxy requires authentication.  I've tried a number of iterations to get the user name, password, proxy and port specified but with no luck. 

Various documentation I've found online suggest defining the ArcGIS Server as follows using the proxy parameter:

`ags = restapi.ArcServer(rest_url, proxy = 'http://username:password@proxy.example.com:8080')`

This typically throws the following error:

`ConnectionError: HTTPConnectionPool(host='proxy.example.com', port=8080): Max retries exceeded with url: /?http://co.kent.de.us/arcgis/rest/services?f=json (Caused by NewConnectionError('<restapi.requests.packages.urllib3.connection.HTTPConnection object at 0x0A2B80F0>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))`

I will mention that I do have special characters in the password I am using and have tried substituting encoded values.

**Comment by CalebM1987** [comment]
Hmm, this seems to me like an issue that may be unique to your proxy.  `restapi` is using a helper function (`restapi.rest_utils.do_proxy_request`) to execute the request through a proxy.  It is stated in the help for the code that this is assumed to be the standard Esri Proxy, something like [this example](https://github.com/Esri/resource-proxy):

``` py
>>> help(restapi.do_proxy_request)
Help on function do_proxy_request in module restapi.rest_utils:

do_proxy_request(proxy, url, params={})
    make request against ArcGIS service through a proxy.  This is designed for a
    proxy page that stores access credentials in the configuration to handle authentication.
    It is also assumed that the proxy is a standard Esri proxy (i.e. retrieved from their
    repo on GitHub)

    Required:
        proxy -- full url to proxy
        url -- service url to make request against
    Optional:
        params -- query parameters, user is responsible for passing in the
            proper parameters

>>> 
```

That being said, I would still think that your proxy would work in a similar manner.  I think this situation could be too unique to be an issue with `restapi`, as I have thoroughly tested using services with the Esri proxy mentioned above.  If you have token based security you can also authenticate with that by passing in a username and password.

However, I would be willing to see if I can help you resolve your issue through personal communication.  I can be emailed at caleb.mackey@gmail.com if you would like to further discuss.

**Comment by green3g** [comment]
I happened to be lurking and recall having a similar problem in the past with python and proxies. We had a corporate proxy set up that used the ntlm protocol and as far as I know, the only way I could get it working was to install yet another proxy on the local machine that would authenticate with the corporate proxy. We used http://cntlm.sourceforge.net/

Basically it works like this:

local python ---> Connects to local CNTLM ---> Authenticates with corporate proxy --> Retrieves WWW

**Comment by CalebM1987** [comment]
@roemhildtg thanks for chiming in.  I have only used the Esri proxy for getting at REST endpoints and always seems to work, but all servers I have tried this with were not using the ntlm protocol.  By the way, I see you are in Fairbualt, MN.  I am in Mankato :)

Mike - One idea I have would be to use the `proxies` parameter of the `requests.post` method.  Looks like your proxy may closely resemble a basic Auth proxy.  The help docs have this [example](http://docs.python-requests.org/en/master/user/advanced/):

> To use HTTP Basic Auth with your proxy, use the http://user:password@host/ syntax:
> 
> `proxies = {'http': 'http://user:pass@10.10.1.10:3128/'}`
> 
> To give a proxy for a specific scheme and host, use the scheme://hostname form for the key. This will match for any request to the given scheme and exact hostname.
> 
> `proxies = {'http://10.20.1.128': 'http://10.10.1.10:5323'}`
> 
> Note that proxy URLs must include the scheme.

And then, to test, you can try something like the following:

```
import requests
import json
proxies = {'http': 'http://username:password@proxy.example.com:8080'}
test = requests.get(rest_url, proxies=proxies)
if test.status_code == 200:
     # success!
     print(json.dumps(r.json(), indent=2))
else:
    # fail
    print('oh no, we suck again!')
```

I also found [this issue](https://github.com/kennethreitz/requests/issues/1582) within the `requests` repo that may be useful.  

Please let me know if this works, and maybe I can support this in `restapi`.  If not, is it possible for you to try and install the proxy from the page listed by @roemhildtg?  Please let me know if either of these solutions work for you.

**Comment by MikeTownshend** [comment]
Thanks for the suggestion to test request.get.   This failed with the response:

```
Traceback (most recent call last):
  File "E:\GISFiles\restapi-master\restapi\testProxy.py", line 5, in <module>
    test = requests.get(rest_url, proxies=proxies)
  File "E:\GISFiles\restapi-master\restapi\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "E:\GISFiles\restapi-master\restapi\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\GISFiles\restapi-master\restapi\requests\sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\GISFiles\restapi-master\restapi\requests\sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "E:\GISFiles\restapi-master\restapi\requests\adapters.py", line 381, in send
    raise ProxyError(e)
ProxyError: Cannot connect to proxy. Socket error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

I will be out of the office for a week and will look into cntlm when I return.

**Comment by green3g** [comment]
I remember our error was something along the lines of "Microsoft forefront tmg could not authenticate..." or something along those lines. Cntlm probably won't help unless you're using Microsofts proxy

**Comment by MikeTownshend** [comment]
Sorry it’s been a while since I’ve been looking at using restapi from behind a proxy.  The answer to your question is yes,  The sample you provided below works once I give it the appropriate proxy URL.
