### ISSUE TITLE
I am not able to make clip functionality work properly.

### ISSUE THREAD

**Issue by mansimittal13** [Bolton-and-Menk-GIS/restapi#8]
Error while using json:
message : 
code : -2147220869
details : [ ]

Error while using polygon feature class:
Not suitable geometry type

Error while using polygon shp file;
'NoneType' object is not iterable

Guide me if anything I can try.

**Comment by CalebM1987** [comment]
Can you post the full code you are using to clip?  This error is not helpful without context.
